esphome:
  name: esp32-cam
  friendly_name: "ESP32 Camera"

esp32:
  board: esp32cam
  framework:
    type: arduino

web_server:
  port: 80

# إعدادات الـ PSRAM مهمة جداً لرفع الدقة ومنع إعادة التشغيل العشوائي
psram:

logger:

api:

ota:
  platform: esphome

wifi:
  ssid: "HAH-M"
  password: "HAHDATA2029"
  fast_connect: true

# تعريف الكاميرا بالـ Pinout القياسي لموديل AI-Thinker
esp32_camera:
  name: "My Camera"
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # جودة ودقة الصورة
  resolution: 640x480        # خيارات شائعة: 640x480 (VGA), 800x600 (SVGA), 1024x768 (XGA)
  jpeg_quality: 10          # القيمة من 10 إلى 63 (كلما قل الرقم زادت الجودة)
  max_framerate: 10.0 fps
  idle_framerate: 0.1 fps   # معدل التحديث عند عدم فتح البث في HA لتوفير الطاقة والحرارة
  vertical_flip: false
  horizontal_mirror: false

# سيرفر محلي للبث المباشر (اختياري للربط مع NVR أو متصفح خارجي)
esp32_camera_web_server:
  - port: 8080
    mode: stream

# تفعيل كشاف الفلاش المدمج (Flashlight LED على GPIO4)
output:
  - platform: ledc
    pin: GPIO4
    id: gpio_flash

light:
  - platform: monochromatic
    output: gpio_flash
    name: "Camera Flashlight"
